base_to_livox_tf:
  ros__parameters:
    use_sim_time: false

base_to_odom_tf:
  ros__parameters:
    use_sim_time: false

controller_server:
  ros__parameters:
    use_sim_time: false
    odom_topic: /mavros/local_position/odom
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.02
    min_y_velocity_threshold: 0.02
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 5.0
    progress_checker_plugin: "progress_checker"
    current_goal_checker: "general_goal_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1
      movement_time_allowance: 10.0
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 3.15
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      lookahead_dist: 0.5
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.8
      use_rotate_to_heading: true
      rotate_to_heading_angular_vel: 0.3
      desired_linear_vel: 0.5
      max_allowed_time_to_collision_up_to_carrot: 1.0
      min_linear_vel: 0.1
      max_linear_vel: 0.6
      max_angular_vel: 1.0
      min_angular_vel: 0.0
      acc_lim_linear: 0.5
      acc_lim_angular: 1.0
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.05
      regulate_linear_vel: true
      allow_backward: false

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: false

straight_planner:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    path_step_m: 0.1
    goal_xy_tolerance: 0.3
    planning_period_s: 1.0
    controller_id: FollowPath
    goal_checker_id: general_goal_checker
    follow_path_action: /follow_path

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 20.0
      publish_frequency: 5.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: false
      rolling_window: true
      width: 10
      height: 10
      resolution: 0.05
      footprint: "[ [0.40, 0.27], [0.40, -0.27], [-0.40, -0.27], [-0.40, 0.27] ]"
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        clear_before_update: true
        observation_sources: pointcloud
        min_obstacle_height: -100.0
        max_obstacle_height: 100.0
        pointcloud:
          topic: /livox/lidar
          obstacle_range: 7.1
          raytrace_range: 7.1
          min_obstacle_height: 0.2
          max_obstacle_height: 0.65
          clearing: true
          marking: true
          inf_is_valid: true
          data_type: "PointCloud2"
          observation_keep_time: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0
        inflation_radius: 1.0
      always_send_full_costmap: true
  local_costmap_client:
    ros__parameters:
      use_sim_time: false
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: false

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: false
    autostart: true
    bond_timeout: 10.0
    node_names: ['controller_server', 'straight_planner']

nav2_input_bridge:
  ros__parameters:
    use_sim_time: false
    local_odom_topic: "/mavros/local_position/odom"
     reference_latitude: 30.8135718
     reference_longitude: 120.8338169
     reference_altitude: 12.318126322268082
#    reference_latitude: 30.7939518
#    reference_longitude: 120.8104288
#    reference_altitude: 12.07629405266946
    goal_input_topic: "/gp_goal"
    uav_goal_input_topic: "/uav/target_gps"
    target_detected_topic: "/target_detected"
    goal_output_topic: "/goal_pose"
    goal_output_frame: "map"
    require_nav_sat_fix: true
    goal_yaw_from_bearing: false
